### ISSUE TITLE
Algebra

### ISSUE THREAD

**Issue by iammanish17** [codeiiest-dev/Algorithms#4]
### Subtopic: 

- Sieve of Eratosthenes
- Linear Diophantine Equations
- Euler's totient function
- Modular Multiplicative Inverse
- Fibonacci Series

#### Checks:

- [ ] explanation
- [ ] implementation
- [ ] references
- [ ] extra problems for practice

**Comment by iammanish17** [comment]
Assign this to me :<

**Comment by sadn1ck** [comment]
This is closed.
