### ISSUE TITLE
Adding contributors

### ISSUE THREAD

**Issue by arnabsen1729** [codeiiest-dev/Algorithms#8]
@all-contributors please add @sadn1ck for code review and maintaining

**Comment by sadn1ck** [comment]
@AllContributors testing

**Comment by sadn1ck** [comment]
YEs this one @arnabsen1729 

@allcontributors add @arnabsen1729 for maintaining the repository

**Comment by arnabsen1729** [comment]
@allcontributors add @arnabsen1729 for maintaining the repository

**Comment by arnabsen1729** [comment]
@allcontributors add @sadn1ck  for maintaining the repository

**Comment by arnabsen1729** [comment]
@allcontributors add @hrahul2605  for maintaining the repository

**Comment by arnabsen1729** [comment]
@allcontributors add @raydwaipayan  for maintaining the repository
